function buttonClicked(){
    let brands = document.getElementById("brands").value
    let category = document.getElementById("category").value
    fetch (`http://makeup-api.herokuapp.com/api/v1/products.json?brand=${brands}&product_type=${category}`)
        .then (response => response.json())
        .then (data =>{
            console.log(data)
            console.log("Brand:",data[0].brand)
            console.log("Product name:",data[0].name)
            console.log("Description:",data[0].description)
            console.log("Price:",data[0].price)
            console.log("Category:",data[0].product_type)
            console.log("Rating:",data[0].rating)
            document.getElementById("display").append((data[0].brand))
            document.getElementById("display1").append((data[0].product_type))
            document.getElementById("display2").append((data[0].name))
            document.getElementById("display3").append((data[0].description))
            document.getElementById("display4").append((data[0].price))
            document.getElementById("display5").append((data[0].rating))

            console.log("Brand:",data[1].brand)
            console.log("Product name:",data[1].name)
            console.log("Description:",data[1].description)
            console.log("Price:",data[1].price)
            console.log("Category:",data[1].product_type)
            console.log("Rating:",data[1].rating)
            document.getElementById("display6").append((data[1].brand))
            document.getElementById("display7").append((data[1].product_type))
            document.getElementById("display8").append((data[1].name))
            document.getElementById("display9").append((data[1].description))
            document.getElementById("display10").append((data[1].price))
            document.getElementById("display11").append((data[1].rating))

            console.log("Brand:",data[2].brand)
            console.log("Product name:",data[2].name)
            console.log("Description:",data[2].description)
            console.log("Price:",data[2].price)
            console.log("Category:",data[2].product_type)
            console.log("Rating:",data[2].rating)
            document.getElementById("display12").append((data[2].brand))
            document.getElementById("display13").append((data[2].product_type))
            document.getElementById("display14").append((data[2].name))
            document.getElementById("display15").append((data[2].description))
            document.getElementById("display16").append((data[2].price))
            document.getElementById("display17").append((data[2].rating))

            console.log("Brand:",data[3].brand)
            console.log("Product name:",data[3].name)
            console.log("Description:",data[3].description)
            console.log("Price:",data[3].price)
            console.log("Category:",data[3].product_type)
            console.log("Rating:",data[3].rating)
            document.getElementById("display18").append((data[3].brand))
            document.getElementById("display19").append((data[3].product_type))
            document.getElementById("display20").append((data[3].name))
            document.getElementById("display21").append((data[3].description))
            document.getElementById("display22").append((data[3].price))
            document.getElementById("display23").append((data[3].rating))
        })
}